FROM httpd:2.4.33-alpine
RUN  apk update \
    apk upgrade;
COPY vhost.conf /usr/local/apache2/conf/vhost.apache.conf
RUN echo "Include /usr/local/apache2/conf/vhost.apache.conf" >> /usr/local/apache2/conf/httpd.conf
